try{
    const main = () =>{
        return document.URL
    }

    main()
}catch(err){
    main()
}
